import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import DynamicUniverse from "../src/components/DynamicUniverse"; // DynamicUniverse 컴포넌트 임포트

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full`}
      >
        <DynamicUniverse /> {/* DynamicUniverse 컴포넌트 렌더링 */}
        <div className="relative z-10 h-full"> {/* 콘텐츠가 배경 위에 오도록 설정 */}
          {children}
        </div>
      </body>
    </html>
  );
}
